/*
1) CREATE A DATABASE
    CREATE DATABASE ECOMDATA
2) CREATE TABLE USERS

    CREATE TABLE USERS
    (EMAIL VARCHAR(25) PRIMARY KEY,
    PASSWORD VARCHAR(10),
    USERNAME VARCHAR(15),
    ADDRESS VARCHAR(50),
    MOBILE VARCHAR(12));

3) CREATE TABLE PRODUCTS
    
    CREATE TABLE PRODUCTS
    (PCODE INT PRIMARY KEY,
    PNAME VARCHAR(15),
    PDESC VARCHAR(50),
    PCAT  VARCHAR(15),
    PRICE INT);

*/

